:nail_care:

diff --git a/tests/symlinks b/tests/symlinks
--- a/tests/symlinks
+++ b/tests/symlinks
@@ -3,6 +3,9 @@
 ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null && pwd)"
 source "$ROOT_DIR/scripts/core/main.sh"
 
+SUCCESS_CHAR="✓"
+ERROR_CHAR="☓"
+
 _validate() {
   local readonly filename="$1"
   log::warning "Validating $filename..."
@@ -10,7 +13,7 @@ _validate() {
     | grep '\- link:' -A10000 \
     | tail -n +2 \
     | cut -d':' -f2 \
-    | xargs -I% bash -c 'printf "% "; (test -f % || test -d %) && echo ✅ || echo ❌' 
+    | xargs -I% bash -c 'printf "% "; (test -f % || test -d %) && echo $SUCCESS_CHAR || echo $ERROR_CHAR' 
   echo
 }
 
@@ -21,6 +24,6 @@ done
 
 echo -e "$result" | head -n -2
 
-if [[ $result == *"❌"* ]]; then
+if [[ $result == *"$ERROR_CHAR"* ]]; then
   exit 1
 fi
