wip

diff --git a/scripts/pkg/batch b/scripts/pkg/batch
--- a/scripts/pkg/batch
+++ b/scripts/pkg/batch
@@ -8,8 +8,34 @@ source "${DOTFILES}/scripts/pkg/aux/batch.sh"
 ##? Install multiple dependencies
 ##?
 ##? Usage:
+##?    batch list <name>
+##?    batch prompt <name>
 ##?    batch <name>
 
+# input parsing
+list=false
+prompt=false
+case "${1:-}" in
+   list) list=true; shift;;
+   prompt) prompt=true; shift;;
+esac
 name="$1"
+
+_list() {
+   batch::dependencies "$name" | xargs | tr ' ' '\n'
+}
+
+if $list; then
+   _list
+   exit 0
+fi
+
+if $prompt && _list | xargs which; then
+   log::warning "There are missing dependencies for the batch $name"
+   if ! feedback::confirmation "Do you want to install it?"; then
+       exit 1
+   fi
+fi
+
 deps="$(batch::dependencies "$name" | str::join)"
 dot pkg add "${deps[@]}"
