Aug-03 10h09: check, core.sh, rg.sh, ...

diff --git a/scripts/package/add b/scripts/package/add
--- a/scripts/package/add
+++ b/scripts/package/add
@@ -3,6 +3,7 @@ set -euo pipefail
 
 source "${DOTFILES}/scripts/core/main.sh"
 source "${DOTFILES}/scripts/core/log.sh"
+source "${DOTFILES}/scripts/package/aux/core.sh"
 
 ##? Install packages
 ##?
@@ -24,27 +25,23 @@ fi
 if [ $# -gt 1 ]; then
    pkg_failures=0
    for package in "$@"; do
-      dot pkg add "$package" || pkg_failures=$((pkg_failures+1))
+      dot pkg add $($prevent_recipe && printf %s '--prevent-recipe') "$package" || pkg_failures=$((pkg_failures+1))
    done
    exit "$pkg_failures"
 fi
 
-_is_installed() {
-   log::success "${package} is already installed"
-}
-
-_installing() {
+_log::installing() {
    log::warning "Attempting to install ${package}..."
 }
 
-package="$1"
-has "$package" && _is_installed && exit 0
+package="$(pkg::alias "$1" "$prevent_recipe")"
 
-dashed_package="$(echo "$package" | tr ' _' '-')"
-file="${DOTFILES}/scripts/package/recipes/${dashed_package}.sh"
+dot pkg check $($prevent_recipe && printf %s '--prevent-recipe') "$package" && exit 0
+
+file="$(pkg::source_file "$package")"
 
 if $prevent_recipe || ! [ -f "$file" ]; then
-   _installing
+   _log::installing
    for pkg_mgr in apt apk pkg yum dnf port emerge pacman brew pnpm yarn npm pip; do
       dot pkg proxy $pkg_mgr add "$package" && exit 0 || true
    done
@@ -53,14 +50,10 @@ fi
 
 source "$file"
 
-has package::is_installed \
-   && package::is_installed &>/dev/null \
-   && _is_installed \
-   && exit 0
-
-_installing
+_log::installing
 package::install && log::success "Finished installing ${package}!"
 
 hash -r 2>/dev/null || true
 source "${HOME}/.bashrc" 2>/dev/null || true
 source "${HOME}/.zshrc" 2>/dev/null || true
+hash -r 2>/dev/null || true
