Apr-19 15h40: fix-gps, health, navi.zsh, ...

diff --git a/scripts/package/add b/scripts/package/add
--- a/scripts/package/add
+++ b/scripts/package/add
@@ -24,13 +24,13 @@ if [[ "$1" == "--prevent-recipe" ]]; then
    shift
 fi
 
-if [ $# -gt 1 ]; then
-   pkg_failures=0
-   for package in "$@"; do
-      dot pkg add "$($prevent_recipe && printf %s '--prevent-recipe')" "$package" || pkg_failures=$((pkg_failures+1))
-   done
-   exit "$pkg_failures"
-fi
+# if [ $# -gt 1 ]; then
+#    pkg_failures=0
+#    for package in "$@"; do
+#       dot pkg add "$($prevent_recipe && printf %s '--prevent-recipe')" "$package" || pkg_failures=$((pkg_failures+1))
+#    done
+#    exit "$pkg_failures"
+# fi
 
 _log::installing() {
    local suffix=""
