Apply formatter (#43)
Fix #35

diff --git a/scripts/shell/zsh b/scripts/shell/zsh
--- a/scripts/shell/zsh
+++ b/scripts/shell/zsh
@@ -7,10 +7,10 @@
 ##?    zsh time <filename>   # Analyzes startup time
 
 if [[ "$1" = "time" ]]; then
-  shift
-else 
-  echo "Invalid arguments"
-  exit 1
+   shift
+else
+   echo "Invalid arguments"
+   exit 1
 fi
 
 typeset -a lines
@@ -18,23 +18,23 @@ typeset -i prev_time=0
 typeset prev_command
 
 while read line; do
-    if [[ $line =~ '^.*\+([0-9]{10})\.([0-9]{6})[0-9]* (.+)' ]]; then
-        integer this_time=$match[1]$match[2]
+   if [[ $line =~ '^.*\+([0-9]{10})\.([0-9]{6})[0-9]* (.+)' ]]; then
+      integer this_time=$match[1]$match[2]
 
-        if [[ $prev_time -gt 0 ]]; then
-            time_difference=$(( $this_time - $prev_time ))
-            lines+="$time_difference $prev_command"
-        fi
+      if [[ $prev_time -gt 0 ]]; then
+         time_difference=$(( $this_time - $prev_time ))
+         lines+="$time_difference $prev_command"
+      fi
 
-        prev_time=$this_time
+      prev_time=$this_time
 
-        local this_command=$match[3]
-        if [[ ${#this_command} -le 80 ]]; then
-            prev_command=$this_command
-        else
-            prev_command="${this_command:0:77}..."
-        fi
-    fi
+      local this_command=$match[3]
+      if [[ ${#this_command} -le 80 ]]; then
+         prev_command=$this_command
+      else
+         prev_command="${this_command:0:77}..."
+      fi
+   fi
 done < ${1:-/dev/stdin}
 
 print -l ${(@On)lines}
