Sep-30 09h52: shortcut, core.sh, intellimacs.sh, ...

diff --git a/scripts/terminal/faketty b/scripts/terminal/faketty
--- a/scripts/terminal/faketty
+++ b/scripts/terminal/faketty
@@ -14,37 +14,37 @@ source "${DOTFILES}/scripts/core/main.sh"
 
 doc::maybe_help "$@"
 
-faketty () {
-  # Create a temporary file for storing the status code
-  tmp=$(mktemp)
+faketty() {
+   # Create a temporary file for storing the status code
+   tmp=$(mktemp)
 
-  # Ensure it worked or fail with status 99
-  [ "$tmp" ] || return 99
+   # Ensure it worked or fail with status 99
+   [ "$tmp" ] || return 99
 
-  # Produce a script that runs the command provided to faketty as
-  # arguments and stores the status code in the temporary file
-  cmd="$(printf '%q ' "$@")"'; echo $? > '$tmp
+   # Produce a script that runs the command provided to faketty as
+   # arguments and stores the status code in the temporary file
+   cmd="$(printf '%q ' "$@")"'; echo $? > '$tmp
 
-  # Run the script through /bin/sh with fake tty
-  if [ "$(uname)" = "Darwin" ]; then
-    # MacOS
-    script -Fq /dev/null /bin/sh -c "$cmd"
-  else
-    script -qfc "/bin/sh -c $(printf "%q " "$cmd")" /dev/null
-  fi
+   # Run the script through /bin/sh with fake tty
+   if [ "$(uname)" = "Darwin" ]; then
+      # MacOS
+      script -Fq /dev/null /bin/sh -c "$cmd"
+   else
+      script -qfc "/bin/sh -c $(printf "%q " "$cmd")" /dev/null
+   fi
 
-  # Ensure that the status code was written to the temporary file or
-  # fail with status 99
-  [ -s $tmp ] || return 99
+   # Ensure that the status code was written to the temporary file or
+   # fail with status 99
+   [ -s $tmp ] || return 99
 
-  # Collect the status code from the temporary file
-  err=$(cat $tmp)
+   # Collect the status code from the temporary file
+   err=$(cat $tmp)
 
-  # Remove the temporary file
-  rm -f $tmp
+   # Remove the temporary file
+   rm -f $tmp
 
-  # Return the status code
-  return $err
+   # Return the status code
+   return $err
 }
 
 faketty "$@"
