Refactor scripts + ./bin/dot

diff --git a/scripts/environment/dependencies b/scripts/environment/dependencies
--- a/scripts/environment/dependencies
+++ b/scripts/environment/dependencies
@@ -3,17 +3,104 @@
 set -euo pipefail
 
 source $DOTFILES/scripts/core/main.sh 
-source $DOTFILES/scripts/aux/install.sh 
-source $DOTFILES/scripts/aux/setup.sh 
+source $DOTFILES/scripts/environment/core.sh 
 
-##? Dependency install
- #? 0.1.0
+##? Installs CLI dependencies
+ #? 0.2.1
 ##?
 ##? Usage:
 ##?    dependencies
 
 eval_docopts "$@"
 
-is_osx && gnu_install; 
-setup; 
+function main() {
+	is_osx && gnu_install; 
+	setup; 
+}
 
+function setup_apt() {
+
+  # Add commons 
+  sudo apt-get install software-properties-common
+
+  # Add third-party repositories
+  for repository in $(from_dependencies "apt-repositories")
+  do
+    sudo add-apt-repository $repository -y
+  done
+  sudo apt-get update -y
+  sudo apt-get upgrade -y
+
+  # Install essential commands
+  for package in $(from_dependencies "brew-apt" "apt")
+  do 
+  sudo apt-get install -y $package
+done
+
+}
+
+function setup_brew() {
+
+  # Install brew
+  if ! command_exists brew ; then
+    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+  fi
+
+  # Install essential commands
+  for package in $(from_dependencies "brew-apt" "brew")
+  do
+    brew install $package
+  done
+
+}
+
+function setup() {
+
+  # Initial setup
+  sudo mkdir -p $HOME/tmp
+  package_manager=$(get_package_manager)
+  dependencies=$(read_dependencies)
+  if [[ -z "$package_manager" ]]; then
+    echo "Unable to find compatible install commands for your platform. Aborting..."
+    exit 1
+  else
+    echo "Detected package manager: $package_manager"
+  fi
+
+  # Invoke platform-specific setup
+  case $package_manager in
+    brew) setup_brew;;
+    apt) setup_apt;;
+  esac
+
+  # Install fzf
+  git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
+  $HOME/.fzf/install
+
+  # Install vim-plug
+  curl -fLo $HOME/.local/share/nvim/site/autoload/plug.vim --create-dirs \
+  http://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+
+  # Install tpm
+  git clone https://github.com/tmux-plugins/tpm --depth=1 $HOME/.tmux/plugins/tpm
+
+  # Install tmuxinator
+  gem install tmuxinator
+
+  # Setup dotfiles
+  cd $HOME/.dotfiles
+  bash install
+
+  # Cleanup
+  rm -rf $HOME/tmp
+  cd $HOME
+
+}
+
+function gnu_install() {
+  brew tap homebrew/dupes
+  brew install binutils diffutils ed findutils gawk gnu-indent gnu-sed gnu-tar gnu-which gnutls grep gzip screen watch  wget && brew install wdiff --with-gettext
+  brew install bash emacs m4 make nano file-formula git less openssh rsync unzip
+}
+
+main "$@"
diff --git a/scripts/environment/dotfiles b/scripts/environment/dotfiles
--- a/scripts/environment/dotfiles
+++ b/scripts/environment/dotfiles
@@ -3,19 +3,78 @@
 set -euo pipefail
 
 source $DOTFILES/scripts/core/main.sh 
-source $DOTFILES/scripts/aux/install.sh 
-source $DOTFILES/scripts/aux/setup.sh 
+source $DOTFILES/scripts/environment/core.sh
 
-##? Dotfiles setup
- #? 0.1.0
+##? Updates submodules, dotfiles and attempts to do some setup
+ #? 0.2.2
 ##?
 ##? Usage:
 ##?    dotfiles
 
 eval_docopts "$@"
 
-  update_dotfiles_prepare;
-  update_dotfiles_common;
-  is_osx && { update_dotfiles_osx; }
-  update_dotfiles_finish;
+DOTBOT_DIR="modules/dotbot"
+DOTBOT_BIN="bin/dotbot"
 
+function main() {
+	update_dotfiles_pre;
+	update_dotfiles_common;
+	is_osx && { update_dotfiles_osx; }
+	update_dotfiles_pos;
+}
+
+update_dotfiles_pre() {
+
+  echo "Setting folder architecture..."
+  mkdir -p "$DOTFILES/local/bin"
+  pushd . > /dev/null
+  cd $DOTFILES
+
+  echo "Attempting to update submodules..."
+  (git pull && git submodule init && git submodule update && git submodule status && \
+    cd "${DOTFILES}" && git submodule update --init --recursive "${DOTBOT_DIR}" || true)
+
+}
+
+update_dotfiles() {
+
+  CONFIG="$DOTFILES/scripts/db/$1"
+  shift
+
+  echo
+  "${DOTFILES}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${DOTFILES}" -c "${CONFIG}" "${@}" 
+  echo
+
+}
+
+update_dotfiles_pos() {
+
+  # Neovim
+  echo "Installing neovim plugins..."
+  nvim +silent +PlugInstall +qall > /dev/null || true
+
+  # Tmux
+  echo "Installing tpm plugins..."
+  export TMUX_PLUGIN_MANAGER_PATH="$HOME/.tmux/plugins/"
+  bash "${TMUX_PLUGIN_MANAGER_PATH}tpm/bin/install_plugins" > /dev/null || true
+  bash "${TMUX_PLUGIN_MANAGER_PATH}tpm/bin/update_plugins" all > /dev/null || true
+
+  # ZPlug
+  echo "Installing ZPlug plugins..."
+  zplug install 2> /dev/null || true
+
+  # Cleanup
+  popd > /dev/null
+
+}
+
+update_dotfiles_common() {
+  update_dotfiles "conf.yaml"
+}
+
+update_dotfiles_osx() {
+  echo "Adding necessary files for OSX"
+  update_dotfiles "conf.osx.yaml"
+}
+
+main "$@"
